version: 2
updates:
  # Python dependencies
  - package-ecosystem: "pip"
    directory: "/packages/api"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5

  - package-ecosystem: "pip"
    directory: "/packages/sdk-python"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5

  # JavaScript dependencies
  - package-ecosystem: "npm"
    directory: "/packages/dashboard"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5

  - package-ecosystem: "npm"
    directory: "/packages/sdk-js"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5

  # GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
